Mappings:
  RegionMap:
    ca-central-1:
      AMI: ami-085edf38cedbea498
    us-east-2:
      AMI: ami-00c03f7f7f2ec15c3
    eu-west-3: 
      AMI: ami-03b4b78aae82b30f1
    eu-north-1: 
      AMI: ami-1b2fa465
    eu-west-2: 
      AMI: ami-00a1270ce1e007c27
    eu-central-1: 
      AMI: ami-00aa4671cbf840d82
    us-west-1: 
      AMI: ami-0245d318c6788de52
    eu-west-1: 
      AMI: ami-0ce71448843cb18a1
    us-west-2: 
      AMI: ami-04b762b4289fba92b
    ap-northeast-2: 
      AMI: ami-0d097db2fb6e0f05e
    ap-south-1: 
      AMI: ami-0cb0e70f44e1a4bb5
    us-east-1: 
      AMI: ami-0b69ea66ff7391e80
    ap-northeast-1: 
      AMI: ami-0ff21806645c5e492
    sa-east-1: 
      AMI: ami-0a1f49a762473adbd
    ap-southeast-2: 
      AMI: ami-03ed5bd63ba378bd8
    ap-southeast-1:
      AMI: ami-048a01c78f7bae4aa

Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", AMI]
      InstanceType: t3a.nano